# Generated by Django 4.2.13 on 2025-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=150)),
                ("locale", models.CharField(blank=True, default="", max_length=10)),
                ("subject_template", models.CharField(max_length=255)),
                ("text_template", models.TextField(blank=True)),
                ("html_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "locale", "is_active"],
                        name="emails_emai_key_f48470_idx",
                    )
                ],
                "unique_together": {("key", "locale", "version")},
            },
        ),
    ]
