# Generated by Django 4.2.13 on 2025-10-10 18:03

import course_player.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("client_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        default=course_player.models.new_session_id,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("progress", models.FloatField(default=0.0)),
                (
                    "completion_status",
                    models.CharField(default="incomplete", max_length=32),
                ),
                ("session_time", models.CharField(default="PT0H0M0S", max_length=32)),
                ("scroll_position", models.IntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("lesson_location", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("cmi_data", models.JSONField(default=dict)),
                ("last_position", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("attempt_index", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("score_percent", models.IntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_sessions",
                        to="client_admin.usercourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField()),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seen_index",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("score_points", models.IntegerField(blank=True, null=True)),
                ("max_points", models.IntegerField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.lesson",
                    ),
                ),
                (
                    "lesson_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_player.lessonsession",
                        verbose_name="Lesson Session",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.question",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="client_admin.quizattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SCORMTrackingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmi_data", models.JSONField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("lesson_location", models.TextField(blank=True, null=True)),
                ("scroll_position", models.IntegerField(default=0)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("failed", "Failed"),
                            ("passed", "Passed"),
                            ("pending", "Pending"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_time", models.CharField(default="PT0H0M0S", max_length=32)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "lesson")},},
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mini_lesson_index", models.IntegerField(blank=True, null=True)),
                ("progress", models.CharField(default="0.0", max_length=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "lesson", "mini_lesson_index")},},
        ),
        migrations.CreateModel(
            name="EssayPromptGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("score_points", models.IntegerField(default=0)),
                ("max_points", models.IntegerField(default=1)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.essayprompt",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_grades",
                        to="course_player.quizresponse",
                    ),
                ),
            ],
            options={"unique_together": {("response", "prompt")},},
        ),
    ]
