# Generated by Django 4.2.13 on 2025-07-22 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_upload_file_title_upload_file_type_upload_url"),
        ("client_admin", "0012_alter_profile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("progress", models.FloatField(default=0.0)),
                (
                    "completion_status",
                    models.CharField(default="incomplete", max_length=32),
                ),
                ("session_time", models.CharField(default="PT0H0M0S", max_length=32)),
                ("scroll_position", models.IntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("lesson_location", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("cmi_data", models.JSONField(default=dict)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_sessions",
                        to="client_admin.usercourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField()),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.lesson",
                    ),
                ),
                (
                    "lesson_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the session during which the answer was submitted.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_player.lessonsession",
                        verbose_name="Lesson Session",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SCORMTrackingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmi_data", models.JSONField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("lesson_location", models.TextField(blank=True, null=True)),
                ("scroll_position", models.IntegerField(default=0)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("failed", "Failed"),
                            ("passed", "Passed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_time", models.CharField(default="PT0H0M0S", max_length=32)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "lesson")},},
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mini_lesson_index", models.IntegerField(blank=True, null=True)),
                ("progress", models.CharField(max_length=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "lesson", "mini_lesson_index")},},
        ),
    ]
