# Generated by Django 4.2.13 on 2025-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=110,
            ),
        ),
    ]
