# Generated by Django 5.1.2 on 2025-06-26 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_id', models.IntegerField(help_text='The session or attempt ID for the quiz.', verbose_name='Sitting ID')),
                ('question_id', models.IntegerField(help_text='The ID of the question being answered.', verbose_name='Question ID')),
                ('user_answer', models.TextField(help_text='The response submitted by the user.', verbose_name='User Answer')),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether the answer is correct (if applicable).', null=True, verbose_name='Is Correct')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz Response',
                'verbose_name_plural': 'Quiz Responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
