# Generated by Django 4.2.13 on 2025-06-23 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
        ("course_player", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scormtrackingdata", unique_together={("user", "lesson")},
        ),
    ]
