# Generated by Django 5.0.1 on 2024-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormtrackingdata',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='cmi_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='completion_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
