# Generated by Django 4.2.13 on 2025-08-25 19:20

import course_player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_player", "0002_alter_lessonsession_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="lessonsession", name="status",),
        migrations.AlterField(
            model_name="lessonsession",
            name="session_id",
            field=models.CharField(
                default=course_player.models.new_session_id,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
