# Generated by Django 5.1.2 on 2025-06-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('course_player', '0002_quizresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresponse',
            options={},
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='question_id',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lesson'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='sitting_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='user_answer',
            field=models.TextField(),
        ),
    ]
