# Generated by Django 5.1.2 on 2025-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0002_remove_scormtrackingdata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormtrackingdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scormtrackingdata',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormtrackingdata',
            name='session_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='cmi_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('passed', 'Passed')], default={}, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
