# Generated by Django 4.2.13 on 2025-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_player", "0003_remove_lessonsession_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
