# Generated by Django 5.1.2 on 2025-06-27 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0003_alter_quizresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='sitting_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The session or attempt ID for the quiz.', verbose_name='Sitting ID'),
        ),
    ]
