# Generated by Django 5.1.2 on 2025-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0003_scormtrackingdata_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormtrackingdata',
            name='lesson_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
