# Generated by Django 4.2.13 on 2025-08-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_quizattempt"),
        ("course_player", "0004_lessonsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="quiz_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="Attempt this answer belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="client_admin.quizattempt",
            ),
        ),
    ]
