# Generated by Django 5.1.2 on 2025-06-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0004_alter_quizresponse_sitting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='sitting_id',
        ),
    ]
