# Generated by Django 5.1.2 on 2025-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0004_scormtrackingdata_lesson_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormtrackingdata',
            name='scroll_position',
            field=models.IntegerField(default=0),
        ),
    ]
