# Generated by Django 5.1.2 on 2025-06-27 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0005_remove_quizresponse_sitting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='sitting_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The session or attempt ID for the quiz.', verbose_name='Sitting ID'),
        ),
    ]
