# Generated by Django 4.2.13 on 2025-08-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0005_alter_quizattempt_attempt_id"),
        ("course_player", "0005_quizresponse_quiz_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresponse",
            name="lesson_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_player.lessonsession",
                verbose_name="Lesson Session",
            ),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="quiz_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="client_admin.quizattempt",
            ),
        ),
    ]
