# Generated by Django 5.1.2 on 2025-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0006_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='mini_lesson_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
