# Generated by Django 4.2.13 on 2025-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_player", "0006_alter_quizresponse_lesson_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="seen_index",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
