# Generated by Django 5.1.2 on 2025-02-06 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_uploadedfile_scorm_entry_point'),
        ('course_player', '0007_lessonprogress_mini_lesson_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson', 'mini_lesson_index')},
        ),
    ]
