# Generated by Django 4.2.13 on 2025-09-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_folder_file_folders"),
        ("course_player", "0007_quizresponse_seen_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="max_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizresponse",
            name="score_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EssayPromptGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("score_points", models.IntegerField(default=0)),
                ("max_points", models.IntegerField(default=1)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.essayprompt",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_grades",
                        to="course_player.quizresponse",
                    ),
                ),
            ],
            options={"unique_together": {("response", "prompt")},},
        ),
    ]
