# Generated by Django 5.1.2 on 2025-06-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0008_quizresponse_sitting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='sitting_id',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='lesson_session',
            field=models.ForeignKey(blank=True, help_text='Link to the session during which the answer was submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, to='course_player.lessonsession', verbose_name='Lesson Session'),
        ),
    ]
