# Generated by Django 5.1.2 on 2025-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0008_alter_lessonprogress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='cmi_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
