# Generated by Django 5.1.2 on 2025-07-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0002_alter_scormtrackingdata_unique_together'),
        ('course_player', '0009_remove_quizresponse_sitting_id_and_more'),
    ]

    operations = [
    ]
