# Generated by Django 5.1.2 on 2025-04-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0024_alter_profile_passportphoto_alter_profile_photoid'),
        ('course_player', '0010_lessonsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='client_admin.usercourse'),
        ),
    ]
