# Generated by Django 5.1.2 on 2025-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_player', '0011_lessonsession_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormtrackingdata',
            name='session_time',
            field=models.CharField(default='PT0H0M0S', max_length=32),
        ),
    ]
