# Generated by Django 4.2.13 on 2025-04-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0039_alter_activitylog_table"),
        ("course_player", "0012_alter_scormtrackingdata_session_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormtrackingdata",
            name="user_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SCORM_tracking_datas",
                to="client_admin.usercourse",
            ),
        ),
    ]
