# Generated by Django 4.2.13 on 2025-04-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_player", "0013_scormtrackingdata_user_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="scormtrackingdata", name="user_course",),
    ]
