name: Update Browserlist DB
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-dep:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}
    - run: make requirements

    - name: Update dependencies
      run: npx browserslist@latest --update-db

    - name: setup testeng-ci
      run: |
        git clone https://github.com/edx/testeng-ci.git
        cd $GITHUB_WORKSPACE/testeng-ci
        pip install -r requirements/base.txt
    - name: create pull request
      id: createpullrequest
      env:
        GITHUB_TOKEN: ${{ secrets.requirements_bot_github_token }}
        GITHUB_USER_EMAIL: ${{ secrets.requirements_bot_github_email }}
      run: |
        cd $GITHUB_WORKSPACE/testeng-ci
        python -m jenkins.pull_request_creator --repo-root=$GITHUB_WORKSPACE \
        --target-branch="master" --base-branch-name="update-browserslist" \
        --commit-message="chore: update browserslist" --pr-title="Update browserslist DB" \
        --pr-body="Updated browserlist DB" --delete-old-pull-requests --output-pr-url-for-github-action
