from django.urls import path, include
from . import views

urlpatterns = [
    path('modify-course/', views.create_or_update_course, name='create_or_update_course'),
    # File Library
    path('file-upload/', views.file_upload, name='file_upload'),
    path('file-delete/', views.file_delete, name='file_delete'),
    path('file-rename/', views.file_rename, name='file_rename'),
    path('folder-create/', views.folder_create, name='folder_create'),
    path('folder-delete/', views.folder_delete, name='folder_delete'),
    path('folder-rename/', views.folder_rename, name='folder_rename'),
    path('move-to-folder/', views.move_to_folder, name='move_to_folder'),
    path('get-folder-children/', views.get_folder_children, name='get_folder_children'), 
    path('folder-path/', views.folder_path, name='folder_path'),

    path('get-users/', views.get_users, name='get_users'),
    path('get-courses/', views.get_courses, name='get_courses'),
    path('delete-course-object/', views.delete_object_ajax, name='delete_object_ajax'),
    path('get-timezones/', views.get_timezones, name='get_timezones'),
    path('get-categories/', views.get_categories, name='get_categories'),
    path('get-quizzes/', views.get_quizzes, name='get_quizzes'),
    path('get-quiz-templates/', views.get_quiz_templates, name='get_quiz_templates'),
    path('create-category/', views.create_category, name='create_category'),
    path('edit-category/', views.edit_category, name='edit_category'),
    path('upload-lesson-file/', views.upload_lesson_file, name='upload_lesson_file'),
    path('create-enrollment-key/', views.create_enrollment_key, name='create_enrollment_key'),
    path('edit-enrollment-key/', views.edit_enrollment_key, name='edit_enrollment_key'),
    path('submit-enrollment-key/', views.submit_enrollment_key, name='submit_enrollment_key'),
    path('manage-assignment/', views.manage_assignment, name='manage_assignment'),

    path('opened-course-data/', views.opened_course_data, name='opened_course_data'),
    path('learner-login-data/', views.learner_login_data, name='learner_login_data'),
    path('get-quiz-data/', views.get_question_data, name='get_question_data'),
    path('create-question/', views.create_question, name='create_question'),
    path('update-question-order/', views.update_question_order, name='update_question_order'),
    path('update-answer-order/', views.update_answer_order, name='update_answer_order'),
    path('delete-question/', views.delete_question, name='delete_question'),
    path('get-answer-data/', views.get_answer_data, name='get_answer_data'),
    path('save-question-data/', views.save_question_data, name='save_question_data'),
    path('save-quiz-settings/', views.save_quiz_settings, name='save_quiz_settings'),
    path('change-question-type/', views.change_question_type, name='change_question_type'),
    path('upload-media/', views.upload_question_media, name='upload_question_media'),
    path('upload-reference/', views.upload_reference, name='upload_reference'),
    path('get-quiz-references/<uuid:uuid>/', views.get_quiz_references, name='get_quiz_references'),
    path('get-subcategories/', views.get_subcategories, name='get_subcategories'),
    path('<int:category_id>/question-count/', views.category_question_count, name='category_question_count'),
    path('create-template/', views.create_template, name='create_template'),
    path('update-template/<int:template_id>/', views.update_quiz_template, name='update_quiz_template'),
]