# Generated by Django 4.2.13 on 2025-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_texture",
            field=models.CharField(
                blank=True, default="none", max_length=64, null=True
            ),
        ),
    ]
