# Generated by Django 4.2.13 on 2024-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="widget", options={"ordering": ["order"]},),
        migrations.RenameField(
            model_name="widget", old_name="widget_type", new_name="title",
        ),
        migrations.RemoveField(model_name="dashboard", name="admin",),
        migrations.RemoveField(model_name="widget", name="data",),
        migrations.RemoveField(model_name="widget", name="position",),
        migrations.AddField(
            model_name="widget",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
