# Generated by Django 4.2.13 on 2024-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0002_alter_widget_options_rename_widget_type_widget_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(default="Description"),
        ),
        migrations.AlterField(
            model_name="dashboard", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content",
            field=models.TextField(default="Widget Text"),
        ),
        migrations.AlterField(
            model_name="widget", name="title", field=models.CharField(max_length=255),
        ),
    ]
