# Generated by Django 4.2.13 on 2025-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0002_header_header_texture"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="footer_texture",
            field=models.CharField(
                blank=True, default="none", max_length=64, null=True
            ),
        ),
    ]
