# Generated by Django 4.2.13 on 2024-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0003_dashboard_is_main_alter_dashboard_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="dashboard", name="description",),
        migrations.AddField(
            model_name="dashboard",
            name="layout",
            field=models.CharField(default="layout1", max_length=50),
        ),
    ]
