# Generated by Django 4.2.13 on 2024-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0004_remove_dashboard_description_dashboard_layout"),
    ]

    operations = [
        migrations.RemoveField(model_name="widget", name="content",),
        migrations.AddField(
            model_name="widget",
            name="type",
            field=models.TextField(default="Widget Type"),
        ),
    ]
