# Generated by Django 4.2.13 on 2024-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0005_remove_widget_content_widget_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="header_background_image",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_icon",
            field=models.CharField(default="fa-regular fa-books", max_length=100),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_subtext",
            field=models.CharField(
                default="Kickstart your online Maritime Education", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_subtext_color",
            field=models.CharField(default="#666666", max_length=7),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_text_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_title",
            field=models.CharField(default="Welcome", max_length=255),
        ),
    ]
