# Generated by Django 4.2.13 on 2024-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0006_dashboard_header_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="header_icon_background_color",
            field=models.CharField(default="#e7e7e7", max_length=7),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="header_icon_color",
            field=models.CharField(default="#183b73", max_length=7),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="header_subtext",
            field=models.CharField(
                default="Kickstart your online Education", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="header_subtext_color",
            field=models.CharField(default="#e7e7e7", max_length=7),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="header_text_color",
            field=models.CharField(default="#e7e7e7", max_length=7),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="header_title",
            field=models.CharField(
                default="Welcome, {{ first_name }} {{ last_name }}", max_length=255
            ),
        ),
    ]
