# Generated by Django 4.2.13 on 2024-08-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0007_dashboard_header_icon_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="header_background_image",
            field=models.URLField(
                blank=True,
                default="/static/images/dashboard/dashboard-placeholder.png",
                max_length=1024,
                null=True,
            ),
        ),
    ]
