# Generated by Django 4.2.13 on 2024-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0008_alter_dashboard_header_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="header_background_image_position",
            field=models.CharField(default="right bottom", max_length=255),
        ),
    ]
