# Generated by Django 4.2.13 on 2024-08-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0009_dashboard_header_background_image_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="widget", name="title",),
    ]
