# Generated by Django 4.2.13 on 2024-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0010_remove_widget_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="widget_icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="widget_icon_background_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="widget_icon_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="widget_subtext",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="widget_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
