# Generated by Django 4.2.13 on 2024-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0011_widget_widget_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="widget_subtext_color",
            field=models.CharField(default="#6b6b6b", max_length=7),
        ),
        migrations.AddField(
            model_name="widget",
            name="widget_title_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
