# Generated by Django 4.2.13 on 2024-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0012_widget_widget_subtext_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="widget_external_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
