# Generated by Django 4.2.13 on 2024-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0013_widget_widget_external_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="header_background_image",
            field=models.URLField(
                blank=True,
                default="/static/images/dashboard/bannerTemplate1.png",
                max_length=1024,
                null=True,
            ),
        ),
    ]
