# Generated by Django 4.2.13 on 2024-09-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0014_alter_dashboard_header_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="custom_templates.dashboard",
            ),
        ),
    ]
