# Generated by Django 4.2.13 on 2024-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0015_alter_widget_dashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_logo",
                    models.URLField(
                        blank=True,
                        default="/static/images/logo/HALO LMS Logo-03.png",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "header_background_color",
                    models.CharField(default="#183b73", max_length=7),
                ),
                (
                    "header_text_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
                (
                    "header_text_hover_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
                (
                    "header_text_background_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
            ],
        ),
    ]
