# Generated by Django 4.2.13 on 2024-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0016_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_logo_display",
            field=models.CharField(
                blank=True, default="No File Selected", max_length=1024, null=True
            ),
        ),
    ]
