# Generated by Django 4.2.13 on 2024-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0017_header_header_logo_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_background_color",
                    models.CharField(default="#183b73", max_length=7),
                ),
                (
                    "header_text_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
                (
                    "header_text_hover_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
                (
                    "header_text_background_color",
                    models.CharField(default="#e7e7e7", max_length=7),
                ),
            ],
        ),
    ]
