# Generated by Django 4.2.13 on 2024-09-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0018_footer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footer",
            old_name="header_text_background_color",
            new_name="footer_text_color",
        ),
        migrations.RemoveField(model_name="footer", name="header_text_color",),
        migrations.RemoveField(model_name="footer", name="header_text_hover_color",),
    ]
