# Generated by Django 4.2.13 on 2025-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0019_rename_header_text_background_color_footer_footer_text_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="widget_title_color",
            field=models.CharField(default="#333333", max_length=7),
        ),
    ]
