# Generated by Django 4.2.13 on 2025-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0020_alter_widget_widget_title_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layout", models.CharField(default="layout1", max_length=50)),
                ("is_logo_disabled", models.BooleanField(default=False)),
                (
                    "login_logo",
                    models.URLField(
                        blank=True,
                        default="/static/images/logo/HALO LMS Logo-03.png",
                        max_length=1024,
                        null=True,
                    ),
                ),
                ("logo_width", models.CharField(default="250px", max_length=7)),
                ("logo_height", models.CharField(default="250px", max_length=7)),
                ("logo_space_bottom", models.CharField(default="250px", max_length=7)),
            ],
        ),
    ]
