# Generated by Django 4.2.13 on 2025-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0021_loginform"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="login_logo_title",
            field=models.CharField(
                blank=True, default="No File Selected", max_length=1024, null=True
            ),
        ),
    ]
