# Generated by Django 4.2.13 on 2025-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0022_loginform_login_logo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginform",
            name="logo_height",
            field=models.CharField(default="250", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_space_bottom",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_width",
            field=models.CharField(default="250", max_length=7),
        ),
    ]
