# Generated by Django 4.2.13 on 2025-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0023_alter_loginform_logo_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="logo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
