# Generated by Django 4.2.13 on 2025-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0024_loginform_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="background_color",
            field=models.CharField(default="#f3f3f3", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="background_image",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="loginform",
            name="background_image_title",
            field=models.CharField(
                blank=True, default="No File Selected", max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="is_background_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
