# Generated by Django 4.2.13 on 2025-04-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0025_loginform_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="background_position",
            field=models.CharField(
                blank=True, default="center", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="background_repeat",
            field=models.CharField(
                blank=True, default="no-repeat", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="background_size",
            field=models.CharField(
                blank=True, default="auto", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="is_background_disabled",
            field=models.BooleanField(default=True),
        ),
    ]
