# Generated by Django 4.2.13 on 2025-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0026_loginform_background_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_background_image",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_enable_transparency",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_space_bottom",
            field=models.CharField(default="40", max_length=7),
        ),
    ]
