# Generated by Django 4.2.13 on 2025-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0027_loginform_form_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_image_title",
            field=models.CharField(
                blank=True, default="No File Selected", max_length=1024, null=True
            ),
        ),
    ]
