# Generated by Django 4.2.13 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0028_loginform_form_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_max_width",
            field=models.CharField(default="320", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_radius",
            field=models.CharField(default="8", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_shadow",
            field=models.CharField(default="2", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_shadow_opacity",
            field=models.CharField(default="0", max_length=7),
        ),
    ]
