# Generated by Django 4.2.13 on 2025-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0029_loginform_form_max_width_loginform_form_radius_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_padding_bottom",
            field=models.CharField(default="18", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_padding_right",
            field=models.CharField(default="18", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_padding_top",
            field=models.CharField(default="18", max_length=7),
        ),
    ]
