# Generated by Django 4.2.13 on 2025-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0030_loginform_form_padding_bottom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_padding_left",
            field=models.CharField(default="18", max_length=7),
        ),
    ]
