# Generated by Django 4.2.13 on 2025-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0031_loginform_form_padding_left"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="form_border_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_border_style",
            field=models.CharField(
                blank=True, default="solid", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="form_border_width",
            field=models.CharField(default="0", max_length=7),
        ),
    ]
