# Generated by Django 4.2.13 on 2025-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0032_loginform_form_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="input_padding_bottom",
            field=models.CharField(default="7", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_padding_left",
            field=models.CharField(default="10", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_padding_right",
            field=models.CharField(default="10", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_padding_top",
            field=models.CharField(default="7", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_border_style",
            field=models.CharField(
                blank=True, default="none", max_length=255, null=True
            ),
        ),
    ]
