# Generated by Django 4.2.13 on 2025-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0033_loginform_input_padding_bottom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="input_background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_text_color",
            field=models.CharField(default="#586370", max_length=7),
        ),
    ]
