# Generated by Django 4.2.13 on 2025-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0034_loginform_input_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="input_width",
            field=models.CharField(default="100", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="background_image",
            field=models.URLField(
                blank=True,
                default="/static/images/dashboard/bannerTemplate2.png",
                max_length=1024,
                null=True,
            ),
        ),
    ]
