# Generated by Django 4.2.13 on 2025-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0035_loginform_input_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="input_border_color",
            field=models.CharField(default="#ececf1", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_font_size",
            field=models.CharField(default="15", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="input_radius",
            field=models.CharField(default="8", max_length=7),
        ),
    ]
