# Generated by Django 4.2.13 on 2025-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0036_loginform_input_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="label_color",
            field=models.CharField(default="#41454d", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="label_font_size",
            field=models.CharField(default="15", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="label_font_weight",
            field=models.CharField(
                blank=True, default="600", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="label_space_bottom",
            field=models.CharField(default="8", max_length=7),
        ),
    ]
