# Generated by Django 4.2.13 on 2025-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0037_loginform_label_color_loginform_label_font_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_color",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_color_hover",
            field=models.CharField(default="#1e90ff", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="label_font_weight",
            field=models.CharField(
                blank=True, default="normal", max_length=255, null=True
            ),
        ),
    ]
