# Generated by Django 4.2.13 on 2025-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0038_loginform_button_color_loginform_button_color_hover_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_border_color",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_border_color_hover",
            field=models.CharField(default="#1e90ff", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_text",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_text_hover",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
