# Generated by Django 4.2.13 on 2025-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0039_loginform_button_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_space_above",
            field=models.CharField(default="8", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="label_space_between",
            field=models.CharField(default="16", max_length=7),
        ),
    ]
