# Generated by Django 4.2.13 on 2025-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0040_loginform_button_space_above_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginform",
            old_name="label_space_between",
            new_name="input_space_between",
        ),
    ]
