# Generated by Django 4.2.13 on 2025-04-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_templates",
            "0041_rename_label_space_between_loginform_input_space_between",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_radius",
            field=models.CharField(default="8", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_width",
            field=models.CharField(default="100", max_length=7),
        ),
    ]
