# Generated by Django 4.2.13 on 2025-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0042_loginform_button_radius_loginform_button_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_padding_bottom",
            field=models.CharField(default="7", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_padding_left",
            field=models.CharField(default="10", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_padding_right",
            field=models.CharField(default="10", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="button_padding_top",
            field=models.CharField(default="7", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_space_above",
            field=models.CharField(default="44", max_length=7),
        ),
    ]
