# Generated by Django 4.2.13 on 2025-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0043_loginform_button_padding_bottom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_font_size",
            field=models.CharField(default="14", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_padding_bottom",
            field=models.CharField(default="8", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_padding_left",
            field=models.CharField(default="16", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_padding_right",
            field=models.CharField(default="16", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_padding_top",
            field=models.CharField(default="8", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_radius",
            field=models.CharField(default="24", max_length=7),
        ),
    ]
