# Generated by Django 4.2.13 on 2025-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0044_loginform_button_font_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="is_forgot_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="button_space_above",
            field=models.CharField(default="56", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="input_space_between",
            field=models.CharField(default="12", max_length=7),
        ),
    ]
