# Generated by Django 4.2.13 on 2025-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0045_loginform_is_forgot_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="forgot_text_decoration",
            field=models.CharField(
                blank=True, default="none", max_length=255, null=True
            ),
        ),
    ]
