# Generated by Django 4.2.13 on 2025-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0046_loginform_forgot_text_decoration"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="forgot_font_size",
            field=models.CharField(default="14", max_length=7),
        ),
    ]
