# Generated by Django 4.2.13 on 2025-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0047_loginform_forgot_font_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="forgot_space_above",
            field=models.CharField(default="4", max_length=7),
        ),
    ]
