# Generated by Django 4.2.13 on 2025-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0048_loginform_forgot_space_above"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="forgot_link_color",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="forgot_link_color_hover",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="forgot_text_decoration_hover",
            field=models.CharField(
                blank=True, default="underline", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="forgot_space_above",
            field=models.CharField(default="6", max_length=7),
        ),
    ]
