# Generated by Django 4.2.13 on 2025-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0049_loginform_forgot_link_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="is_signup_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
