# Generated by Django 4.2.13 on 2025-04-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0050_loginform_is_signup_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="signup_font_size",
            field=models.CharField(default="14", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_link_color",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_link_color_hover",
            field=models.CharField(default="#1863dc", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_space_above",
            field=models.CharField(default="6", max_length=7),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_text_decoration",
            field=models.CharField(
                blank=True, default="none", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_text_decoration_hover",
            field=models.CharField(
                blank=True, default="underline", max_length=255, null=True
            ),
        ),
    ]
