# Generated by Django 4.2.13 on 2025-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0051_loginform_signup_font_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginform",
            name="button_font_weight",
            field=models.CharField(
                blank=True, default="normal", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_font_weight",
            field=models.CharField(
                blank=True, default="normal", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginform",
            name="signup_text_color",
            field=models.CharField(default="#333333", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="signup_space_above",
            field=models.CharField(default="20", max_length=7),
        ),
    ]
