# Generated by Django 4.2.13 on 2025-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0052_loginform_button_font_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginform",
            name="background_position",
            field=models.CharField(
                blank=True, default="right center", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="background_size",
            field=models.CharField(
                blank=True, default="cover", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_max_width",
            field=models.CharField(default="380", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_padding_bottom",
            field=models.CharField(default="24", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_radius",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_shadow",
            field=models.CharField(default="0", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="label_space_bottom",
            field=models.CharField(default="6", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_height",
            field=models.CharField(default="70", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_space_bottom",
            field=models.CharField(default="75", max_length=7),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="logo_width",
            field=models.CharField(default="190", max_length=7),
        ),
    ]
