# Generated by Django 4.2.13 on 2025-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0053_alter_loginform_background_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="header_logo_display",
            field=models.CharField(
                blank=True, default="No file selected", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="background_image_title",
            field=models.CharField(
                blank=True, default="No file selected", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="form_image_title",
            field=models.CharField(
                blank=True, default="No file selected", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginform",
            name="login_logo_title",
            field=models.CharField(
                blank=True, default="No file selected", max_length=1024, null=True
            ),
        ),
    ]
