# Generated by Django 4.2.13 on 2025-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0054_alter_header_header_logo_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="widget_title_color",
            field=models.CharField(default="#41454d", max_length=7),
        ),
    ]
