# Generated by Django 4.2.13 on 2025-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_templates", "0055_alter_widget_widget_title_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="widget_subtext_color",
            field=models.CharField(default="#798292", max_length=7),
        ),
    ]
