# Generated by Django 4.2.13 on 2025-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_performer", models.CharField(max_length=150)),
                ("action_target", models.CharField(max_length=150)),
                ("action_type", models.CharField(max_length=150)),
                ("action", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_groups",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "activitylog", "managed": False,},
        ),
    ]
