# Generated by Django 4.2.13 on 2024-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=30, verbose_name="Username"),
        ),
    ]
