# Generated by Django 4.2.13 on 2025-06-17 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermoduleprogress",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.module"
            ),
        ),
        migrations.AddField(
            model_name="usermoduleprogress",
            name="user_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_progresses",
                to="client_admin.usercourse",
            ),
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
            ),
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="user_module_progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progresses",
                to="client_admin.usermoduleprogress",
            ),
        ),
        migrations.AddField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.course"
            ),
        ),
        migrations.AddField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_opened_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.course",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="allowed_id_photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="OrganizationSettings",
                to="client_admin.allowedidphotos",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedcertificate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedcertificate",
            name="user_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="client_admin.usercourse",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentkey",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrollment_keys", to="content.course"
            ),
        ),
    ]
