# Generated by Django 4.2.13 on 2025-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="portal_favicon",
            field=models.ImageField(
                blank=True,
                default="static/images/favicon/16x16.png",
                null=True,
                upload_to="logos/",
            ),
        ),
    ]
