# Generated by Django 4.2.13 on 2024-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="passportphoto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photoid",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
