# Generated by Django 4.2.13 on 2025-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0002_allowedidphotos_timezone_usercourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="date_format",
            field=models.CharField(
                blank=True, default="MM/DD/YYYY", max_length=255, null=True
            ),
        ),
    ]
