# Generated by Django 4.2.13 on 2024-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lms_name", models.CharField(default="LMS", max_length=255)),
                ("organization_name", models.CharField(max_length=255)),
                ("contact_first_name", models.CharField(max_length=255)),
                ("contact_last_name", models.CharField(max_length=255)),
                ("contact_address", models.CharField(max_length=255)),
                ("contact_city", models.CharField(max_length=255)),
                ("contact_state", models.CharField(max_length=255)),
                ("contact_country", models.CharField(max_length=255)),
                ("contact_postal_code", models.CharField(max_length=20)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                ("on_login_course", models.BooleanField(default=False)),
                ("profile_customization", models.BooleanField(default=False)),
            ],
        ),
    ]
