# Generated by Django 4.2.13 on 2025-04-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0002_alter_organizationsettings_portal_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="portal_favicon",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
