# Generated by Django 5.1.2 on 2025-06-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0002_alter_profile_user'),
        ('client_admin', '0002_initial'),
    ]

    operations = [
    ]
