# Generated by Django 4.2.13 on 2024-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0003_alter_profile_passportphoto_alter_profile_photoid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="passportphoto",
            field=models.ImageField(default="Identification Photo", upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="photoid",
            field=models.ImageField(default="ID Photo", upload_to=""),
            preserve_default=False,
        ),
    ]
