# Generated by Django 4.2.13 on 2025-04-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0003_alter_organizationsettings_portal_favicon"),
    ]

    operations = [
        migrations.AlterModelOptions(name="activitylog", options={},),
    ]
