# Generated by Django 4.2.13 on 2024-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0003_organizationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="contact_state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="lms_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="on_login_course",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="profile_customization",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
