# Generated by Django 4.2.13 on 2025-07-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client_admin", "0003_userassignmentprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userassignmentprogress",
            name="approved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userassignmentprogress",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="user_assignments/"
            ),
        ),
        migrations.AddField(
            model_name="userassignmentprogress",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userassignmentprogress",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
