# Generated by Django 4.2.13 on 2024-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_alter_organizationsettings_contact_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="lms_name",
            field=models.CharField(
                blank=True, default="LMS Name", max_length=255, null=True
            ),
        ),
    ]
