# Generated by Django 4.2.13 on 2025-08-26 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_quizattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="attempt_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
