# Generated by Django 4.2.13 on 2025-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_userassignmentprogress_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userassignmentprogress", name="approved",),
        migrations.RemoveField(model_name="userassignmentprogress", name="completed",),
        migrations.AddField(
            model_name="userassignmentprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
