# Generated by Django 4.2.13 on 2025-04-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_alter_activitylog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="activitylog", options={"managed": False},),
    ]
