# Generated by Django 4.2.13 on 2025-07-17 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_upload_file_title_upload_file_type_upload_url"),
        ("client_admin", "0005_remove_userassignmentprogress_approved_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userassignmentprogress",
            unique_together={("user", "assignment", "lesson")},
        ),
    ]
