# Generated by Django 4.2.13 on 2025-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0005_alter_quizattempt_attempt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
