# Generated by Django 4.2.13 on 2024-09-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0005_alter_organizationsettings_lms_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="date_format",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
