# Generated by Django 4.2.13 on 2025-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0005_alter_activitylog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="generated_certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
