# Generated by Django 4.2.13 on 2025-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0006_alter_quizattempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("failed", "Failed"),
                    ("passed", "Passed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
