# Generated by Django 4.2.13 on 2025-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0006_alter_userassignmentprogress_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userassignmentprogress",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
