# Generated by Django 4.2.13 on 2025-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0007_userlessonprogress_completion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="question_order",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="userlessonprogress",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("incomplete", "Incomplete"),
                    ("failed", "Failed"),
                    ("passed", "Passed"),
                    ("pending", "Pending"),
                ],
                default="incomplete",
                max_length=50,
            ),
        ),
    ]
