# Generated by Django 4.2.13 on 2024-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0007_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="time_zone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
