# Generated by Django 4.2.13 on 2025-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0007_userassignmentprogress_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userassignmentprogress",
            name="student_notes",
            field=models.TextField(blank=True),
        ),
    ]
