# Generated by Django 4.2.13 on 2025-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0008_generatedcertificate_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationsettings", name="default_certificate_image",
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="default_certificate_template",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
