# Generated by Django 4.2.13 on 2025-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0008_quizattempt_question_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="enable_gamification",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="learning_credits_name",
            field=models.CharField(
                blank=True, default="HELMS° Credits", max_length=255, null=True
            ),
        ),
    ]
