# Generated by Django 4.2.13 on 2024-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0008_organizationsettings_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="on_login_course_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
