# Generated by Django 4.2.13 on 2025-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0008_userassignmentprogress_student_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userassignmentprogress",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userassignmentprogress",
            name="student_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
