# Generated by Django 4.2.13 on 2024-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0009_organizationsettings_on_login_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="default_course_thumbnail",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
