# Generated by Django 4.2.13 on 2025-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0009_organizationsettings_enable_gamification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="learning_credits_icon",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
