# Generated by Django 4.2.13 on 2025-05-06 15:16

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        (
            "client_admin",
            "0009_remove_organizationsettings_default_certificate_image_and_more",
        ),
    ]

    operations = []
