# Generated by Django 4.2.13 on 2025-07-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_upload_file_title_upload_file_type_upload_url"),
        ("client_admin", "0009_alter_userassignmentprogress_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userassignmentprogress",
            name="course",
            field=models.ForeignKey(
                default=43,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.course",
            ),
            preserve_default=False,
        ),
    ]
