# Generated by Django 5.1.2 on 2025-07-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0004_alter_profile_timezone'),
        ('client_admin', '0010_userassignmentprogress_course'),
    ]

    operations = [
    ]
