# Generated by Django 4.2.13 on 2025-09-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client_admin", "0010_organizationsettings_learning_credits_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_slug", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("criteria", models.JSONField(default=dict)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="badges/org/"),
                ),
                (
                    "icon_static",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_badges",
                        to="client_admin.organizationsettings",
                    ),
                ),
            ],
            options={"unique_together": {("organization", "template_slug")},},
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "org_badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="client_admin.orgbadge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "org_badge")},},
        ),
    ]
