# Generated by Django 4.2.13 on 2024-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0010_organizationsettings_default_course_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="default_course_thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
