# Generated by Django 4.2.13 on 2025-05-06 15:46

from django.db import migrations

def populate_common_timezones(apps, schema_editor):
    TimeZone = apps.get_model('client_admin', 'TimeZone')
    
    COMMON_TIMEZONES = [
        ("UTC", "UTC"),
        ("America/New_York", "(UTC-05:00) Eastern Time (US & Canada)"),
        ("America/Chicago", "(UTC-06:00) Central Time (US & Canada)"),
        ("America/Denver", "(UTC-07:00) Mountain Time (US & Canada)"),
        ("America/Los_Angeles", "(UTC-08:00) Pacific Time (US & Canada)"),
        ("Europe/London", "(UTC+00:00) London"),
        ("Europe/Paris", "(UTC+01:00) Paris"),
        ("Asia/Kolkata", "(UTC+05:30) India Standard Time"),
        ("Asia/Tokyo", "(UTC+09:00) Japan Standard Time"),
        ("Australia/Sydney", "(UTC+10:00) Sydney"),
    ]

    for _, label in COMMON_TIMEZONES:
        TimeZone.objects.get_or_create(name=label)

class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0010_auto_20250506_1116"),
    ]

    operations = [
        migrations.RunPython(populate_common_timezones),
    ]
