# Generated by Django 4.2.13 on 2025-07-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0004_alter_profile_timezone"),
        ("client_admin", "0010_userassignmentprogress_course"),
    ]

    operations = []
