# Generated by Django 4.2.13 on 2024-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0011_organizationsettings_default_course_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="default_certificate",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="default_certificate_image",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
