# Generated by Django 4.2.13 on 2025-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0011_auto_20250506_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="iana_name",
            field=models.CharField(
                default="America/New_York", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="time_zone",
            field=models.CharField(
                blank=True,
                default="(UTC-05:00) Eastern Time (US & Canada)",
                max_length=255,
                null=True,
            ),
        ),
    ]
