# Generated by Django 4.2.13 on 2025-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0012_currencytransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address_1",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="associate_school",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citizenship",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="code",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="initials",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="State/Province"
            ),
        ),
    ]
