# Generated by Django 4.2.13 on 2025-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0012_alter_profile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("conversation", "Conversation"),
                    ("alert", "Alert"),
                    ("system", "System Message"),
                ],
                default="conversation",
                max_length=20,
            ),
        ),
    ]
