# Generated by Django 4.2.13 on 2025-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0012_organizationsettings_iana_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="terms_and_conditions",
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
