# Generated by Django 4.2.13 on 2024-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0013_organizationsettings_portal_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="default_certificate_image",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="portal_favicon",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
