# Generated by Django 4.2.13 on 2025-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0013_organizationsettings_terms_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="terms_and_conditions_text",
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="terms_and_conditions",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
