# Generated by Django 4.2.13 on 2025-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0013_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("alert", "Alert"),
                    ("system", "System Message"),
                ],
                default="message",
                max_length=20,
            ),
        ),
    ]
