# Generated by Django 4.2.13 on 2025-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0014_alter_message_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="check_frequency_time",
            field=models.DurationField(
                blank=True,
                help_text="Customize how often verification checks will occur within a session.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="course_launch_verification",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="in_session_checks",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
