# Generated by Django 4.2.13 on 2025-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "client_admin",
            "0014_organizationsettings_terms_and_conditions_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="terms_and_conditions_text",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
