# Generated by Django 5.0.1 on 2024-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0014_alter_organizationsettings_default_certificate_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_performer', models.CharField(max_length=150)),
                ('action_target', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_groups', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activitylog',
                'managed': False,
            },
        ),
    ]
