# Generated by Django 4.2.13 on 2025-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0015_alter_organizationsettings_terms_and_conditions_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message", name="body", field=models.TextField(max_length=2000),
        ),
    ]
