# Generated by Django 4.2.13 on 2024-10-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0015_activitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(name="activitylog", options={},),
    ]
