# Generated by Django 4.2.13 on 2025-08-06 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0015_organizationsettings_check_frequency_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="check_frequency_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=900),
                help_text="Customize how often verification checks will occur within a session.",
                null=True,
            ),
        ),
    ]
