# Generated by Django 4.2.13 on 2025-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0016_alter_message_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="completed_on_login_course",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="terms_and_conditions_text",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
