# Generated by Django 4.2.13 on 2025-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0017_profile_accepted_terms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="accepted_terms", new_name="terms_accepted",
        ),
        migrations.AddField(
            model_name="profile",
            name="accepted_terms_version",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
