# Generated by Django 4.2.13 on 2025-08-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0017_facialverificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facialverificationlog",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("course_launch_verification", "Course Launch"),
                    ("in_session_check", "In-Session Check"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
