# Generated by Django 4.2.13 on 2025-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0018_rename_accepted_terms_profile_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="terms_and_conditions_text",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
