# Generated by Django 4.2.13 on 2024-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0018_profile_last_opened_course_profile_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlessonprogress", options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="usermoduleprogress", options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usermoduleprogress",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
