# Generated by Django 4.2.13 on 2025-08-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_folder_file_folders"),
        ("client_admin", "0018_alter_facialverificationlog_verification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="facialverificationlog",
            name="browser",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="facialverificationlog",
            name="device_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="facialverificationlog",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.lesson",
            ),
        ),
        migrations.AddField(
            model_name="facialverificationlog",
            name="similarity_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
