# Generated by Django 4.2.13 on 2025-08-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0019_facialverificationlog_browser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facialverificationlog",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verified", "Verified"),
                    ("no_face_live", "No Face Detected"),
                    ("face_mismatch", "Different Face Than Expected"),
                    ("no_face_uploaded", "No Headshot Face Detected"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
