# Generated by Django 4.2.13 on 2025-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0019_alter_organizationsettings_terms_and_conditions_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="terms_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
