# Generated by Django 4.2.13 on 2025-08-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0020_alter_facialverificationlog_error_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationsettings",
            old_name="contact_country",
            new_name="country",
        ),
    ]
