# Generated by Django 4.2.13 on 2025-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0020_organizationsettings_terms_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="lms_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
