# Generated by Django 5.1.2 on 2025-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0021_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='lesson_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
