# Generated by Django 4.2.13 on 2025-08-13 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0021_rename_contact_country_organizationsettings_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="check_frequency_time",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=600),
                help_text="Customize how often verification checks will occur within a session.",
                null=True,
            ),
        ),
    ]
