# Generated by Django 4.2.13 on 2025-05-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_category_parent_category_alter_course_category"),
        ("client_admin", "0021_alter_organizationsettings_lms_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.course"
                    ),
                ),
            ],
        ),
    ]
