# Generated by Django 4.2.13 on 2025-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_category_parent_category_alter_course_category"),
        ("client_admin", "0022_enrollmentkey"),
    ]

    operations = [
        migrations.RemoveField(model_name="enrollmentkey", name="course",),
        migrations.AddField(
            model_name="enrollmentkey",
            name="courses",
            field=models.ManyToManyField(
                related_name="enrollment_keys", to="content.course"
            ),
        ),
        migrations.AddField(
            model_name="enrollmentkey",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
