# Generated by Django 5.1.2 on 2025-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0022_usercourse_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
