# Generated by Django 5.1.2 on 2025-04-17 15:46

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin', '0023_usercourse_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passportphoto',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photoid',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
