# Generated by Django 4.2.13 on 2025-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_category_parent_category_alter_course_category"),
        (
            "client_admin",
            "0023_remove_enrollmentkey_course_enrollmentkey_courses_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentkey",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrollment_keys", to="content.course"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentkey",
            name="uses",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
