# Generated by Django 4.2.13 on 2025-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0024_alter_enrollmentkey_courses_alter_enrollmentkey_uses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentkey",
            name="max_uses",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="enrollmentkey",
            name="uses",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
