# Generated by Django 4.2.13 on 2025-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0025_alter_profile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedIdPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="allowed_id_photos",
            field=models.ManyToManyField(
                related_name="organizations", to="client_admin.allowedidphotos"
            ),
        ),
    ]
