# Generated by Django 4.2.13 on 2025-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0025_alter_enrollmentkey_max_uses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_opened_lesson_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
