# Generated by Django 4.2.13 on 2025-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0026_allowedidphotos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsettings",
            name="allowed_id_photos",
            field=models.ManyToManyField(
                related_name="OrganizationSettingss", to="client_admin.allowedidphotos"
            ),
        ),
    ]
