# Generated by Django 4.2.13 on 2025-05-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_category_parent_category_alter_course_category"),
        ("client_admin", "0026_profile_last_opened_lesson_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_opened_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.course",
            ),
        ),
    ]
