# Generated by Django 4.2.13 on 2025-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0027_alter_organizationsettings_allowed_id_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedidphotos",
            name="description",
            field=models.CharField(default="test", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="allowed_id_photos",
            field=models.ManyToManyField(
                related_name="OrganizationSettings", to="client_admin.allowedidphotos"
            ),
        ),
    ]
