# Generated by Django 4.2.13 on 2025-04-16 12:53
from django.db import migrations, models
import uuid

def generate_unique_uuids(apps, schema_editor):
    UserCourse = apps.get_model('client_admin', 'UserCourse')
    for user_course in UserCourse.objects.all():
        user_course.uuid = uuid.uuid4()
        user_course.save()

class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0028_allowedidphotos_description_and_more"),
    ]

    operations = [
        # Step 1: Add nullable UUID field first
        migrations.AddField(
            model_name="usercourse",
            name="uuid",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),

        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(generate_unique_uuids),

        # Step 3: Enforce uniqueness and non-null
        migrations.AlterField(
            model_name="usercourse",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # Preserve your existing alteration to OrganizationSettings
        migrations.AlterField(
            model_name="organizationsettings",
            name="allowed_id_photos",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="OrganizationSettings",
                to="client_admin.allowedidphotos",
            ),
        ),
    ]
