# Generated by Django 4.2.13 on 2025-04-16 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0029_usercourse_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercourse",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
