# Generated by Django 4.2.13 on 2025-04-17 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0030_alter_usercourse_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="stored_progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
