# Generated by Django 4.2.13 on 2025-04-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0031_usercourse_stored_progress_alter_usercourse_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="completed_on_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercourse",
            name="completed_on_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("completed_on", "Completed On")], max_length=20
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("from_enrollment", models.JSONField(blank=True, null=True)),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dates",
                        to="client_admin.usercourse",
                    ),
                ),
            ],
        ),
    ]
