# Generated by Django 4.2.13 on 2025-04-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0032_usercourse_completed_on_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CourseActivity",),
    ]
