# Generated by Django 4.2.13 on 2025-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0033_delete_courseactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_course_completed",
            field=models.BooleanField(default=False),
        ),
    ]
