# Generated by Django 4.2.13 on 2025-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0034_usercourse_is_course_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="completed_on_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userlessonprogress",
            name="completed_on_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
