# Generated by Django 4.2.13 on 2025-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0035_userlessonprogress_completed_on_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
