# Generated by Django 4.2.13 on 2025-04-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0024_alter_profile_passportphoto_alter_profile_photoid"),
        ("client_admin", "0036_userlessonprogress_attempts"),
    ]

    operations = []
