# Generated by Django 4.2.13 on 2025-04-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0037_merge_20250422_1014"),
    ]

    operations = [
        migrations.AlterModelTable(name="activitylog", table=None,),
    ]
