# Generated by Django 4.2.13 on 2025-04-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0038_alter_activitylog_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="activitylog", table="activitylog",),
    ]
