# Generated by Django 4.2.13 on 2025-04-24 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("client_admin", "0039_alter_activitylog_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="enrollment_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
