# Generated by Django 4.2.13 on 2024-08-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="none", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("bundle", "Course Bundle"),
                    ("in_person", "In Person Course"),
                    ("online", "Online Course"),
                ],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default="none",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="content.category",
            ),
        ),
    ]
