# Generated by Django 4.2.13 on 2025-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="assignment_toggle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="assignments",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="content.upload"
            ),
        ),
    ]
