# Generated by Django 4.2.13 on 2024-08-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="user_files/")),
                ("title", models.CharField(default="Untitled", max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="SCORMContent",),
        migrations.DeleteModel(name="StorylineQuizContent",),
        migrations.DeleteModel(name="TextContent",),
        migrations.DeleteModel(name="VideoContent",),
        migrations.RemoveField(model_name="lesson", name="content_type",),
        migrations.RemoveField(model_name="lesson", name="object_id",),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("bundle", "Course Bundle"),
                    ("in_person", "In Person Course"),
                    ("online", "Online Course"),
                ],
                default="bundle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.category",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.file",
            ),
        ),
    ]
