# Generated by Django 4.2.13 on 2024-08-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("bundle", "Course Bundle"),
                    ("in_person", "In Person Course"),
                    ("online", "Online Course"),
                ],
                default="bundle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.category",
            ),
        ),
    ]
