# Generated by Django 5.0.6 on 2024-08-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('bundle', 'Course Bundle'), ('in_person', 'In Person Course'), ('online', 'Online Course')], default='bundle', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
    ]
