# Generated by Django 4.2.13 on 2025-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="quizzes",
                through="content.QuestionOrder",
                to="content.question",
            ),
        ),
    ]
