# Generated by Django 4.2.13 on 2024-08-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_category_file_delete_scormcontent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("certificate", "Certificate")], max_length=20
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("source", models.URLField(blank=True, max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="content.course",
                    ),
                ),
            ],
        ),
    ]
