# Generated by Django 4.2.13 on 2025-05-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_quiz_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FITBQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.question",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, answers must match exactly including case.",
                        verbose_name="Case Sensitive",
                    ),
                ),
                (
                    "strip_whitespace",
                    models.BooleanField(
                        default=True,
                        help_text="Trim leading/trailing whitespace before checking answer.",
                        verbose_name="Strip Whitespace",
                    ),
                ),
            ],
            bases=("content.question",),
        ),
        migrations.CreateModel(
            name="MCQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.question",
                    ),
                ),
                (
                    "answer_order",
                    models.CharField(
                        blank=True,
                        default="none",
                        help_text="The order in which multichoice answer options are displayed to the user",
                        max_length=30,
                        null=True,
                        verbose_name="Answer Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "verbose_name_plural": "Multiple Choice Questions",
            },
            bases=("content.question",),
        ),
        migrations.CreateModel(
            name="TFQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.question",
                    ),
                ),
                (
                    "correct",
                    models.BooleanField(
                        help_text="Select 'True' if the correct answer is True, else 'False'.",
                        verbose_name="Correct Answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "True/False Question",
                "verbose_name_plural": "True/False Questions",
            },
            bases=("content.question",),
        ),
        migrations.CreateModel(
            name="FITBAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=255, verbose_name="Acceptable Answer"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptable_answers",
                        to="content.fitbquestion",
                    ),
                ),
            ],
        ),
    ]
