# Generated by Django 4.2.13 on 2025-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_eventdate_course_eventdate_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdate",
            name="type",
            field=models.CharField(
                choices=[
                    ("start_date", "Start Date"),
                    ("expiration_date", "Expiration Date"),
                    ("due_date", "Due Date"),
                    ("certificate_expiration_date", "Expiration Date"),
                ],
                max_length=50,
            ),
        ),
    ]
