# Generated by Django 4.2.1 on 2024-09-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_credential_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_completion_time',
            field=models.DurationField(blank=True, help_text='Estimated time to complete the course (e.g., 3 hours)', null=True),
        ),
    ]
