# Generated by Django 4.2.13 on 2025-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_lesson_assignment_toggle_lesson_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="file_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
