# Generated by Django 4.2.13 on 2024-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_category_file_delete_scormcontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
