# Generated by Django 4.2.13 on 2024-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_category_course_status_course_type_course_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=200),
        ),
    ]
