# Generated by Django 4.2.1 on 2024-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_estimated_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='must_complete',
            field=models.CharField(choices=[('any_order', 'All lessons, in any order'), ('by_chapter', 'All lessons, in order by chapter')], default='any_order', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
