# Generated by Django 4.2.1 on 2024-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('scorm', 'SCORM'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
