# Generated by Django 4.2.13 on 2024-08-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_credential"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("start_date", "Start Date"),
                            ("expiration_date", "Expiration Date"),
                            ("due_date", "Due Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("from_enrollment", models.JSONField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dates",
                        to="content.course",
                    ),
                ),
            ],
        ),
    ]
