# Generated by Django 4.2.13 on 2025-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_fitbquestion_mcquestion_tfquestion_fitbanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
