# Generated by Django 4.2.13 on 2025-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_answer_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitbanswer",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
