# Generated by Django 4.2.13 on 2024-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_course_must_complete_course_terms_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
