# Generated by Django 4.2.13 on 2025-04-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_eventdate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_credential",
                to="content.credential",
            ),
        ),
    ]
