# Generated by Django 4.2.13 on 2024-08-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_eventdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail_link", models.URLField(blank=True, max_length=500)),
                (
                    "thumbnail_image",
                    models.ImageField(blank=True, upload_to="thumbnails/"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="content.course",
                    ),
                ),
            ],
        ),
    ]
