# Generated by Django 4.2.13 on 2025-06-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_fitbanswer_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="answer", options={"ordering": ["order"]},),
        migrations.AlterModelOptions(
            name="fitbanswer", options={"ordering": ["order"]},
        ),
    ]
