# Generated by Django 4.2.13 on 2024-09-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_reference_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("reference", "Reference")], max_length=20
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("file", models.FileField(upload_to="references/")),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="content.course",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Reference",),
    ]
