# Generated by Django 4.2.13 on 2025-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_lesson_description_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="course",
            name="upload_instructions",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="resources",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
