# Generated by Django 4.2.13 on 2024-09-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_resources_delete_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="content.course",
            ),
        ),
    ]
