# Generated by Django 4.2.13 on 2025-06-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_answer_options_alter_fitbanswer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="randomize_answer_order",
            field=models.BooleanField(
                default=False,
                help_text="Display the answers in a random order when the question is shown.",
                verbose_name="Randomize Answer Order",
            ),
        ),
    ]
