# Generated by Django 4.2.13 on 2024-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_resources_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="file",
            field=models.FileField(upload_to="resources/"),
        ),
    ]
