# Generated by Django 4.2.13 on 2025-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_question_randomize_answer_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcquestion",
            name="allows_multiple",
            field=models.BooleanField(default=False),
        ),
    ]
