# Generated by Django 4.2.13 on 2025-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_mcquestion_allows_multiple"),
    ]

    operations = [
        migrations.RemoveField(model_name="mcquestion", name="allows_multiple",),
        migrations.AddField(
            model_name="question",
            name="allows_multiple",
            field=models.BooleanField(default=False),
        ),
    ]
