# Generated by Django 4.2.13 on 2024-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_resources_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="resources", name="file",),
        migrations.AddField(
            model_name="resources",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
