# Generated by Django 4.2.13 on 2025-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_remove_mcquestion_allows_multiple_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="fitbquestion", name="case_sensitive",),
        migrations.RemoveField(model_name="fitbquestion", name="strip_whitespace",),
        migrations.AddField(
            model_name="question",
            name="case_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, answers must match exactly including case.",
                verbose_name="Case Sensitive",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="strip_whitespace",
            field=models.BooleanField(
                default=True,
                help_text="Trim leading/trailing whitespace before checking answer.",
                verbose_name="Strip Whitespace",
            ),
        ),
    ]
