# Generated by Django 4.2.13 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
