# Generated by Django 4.2.13 on 2024-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="file_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Inactive",
                max_length=20,
            ),
        ),
    ]
