# Generated by Django 4.2.13 on 2025-06-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_remove_question_case_sensitive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.question",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="General instructions for answering this essay question.",
                        null=True,
                        verbose_name="Instructions",
                    ),
                ),
                (
                    "rubric",
                    models.TextField(
                        blank=True,
                        help_text="Detailed grading rubric for instructors or AI.",
                        null=True,
                        verbose_name="Rubric",
                    ),
                ),
                (
                    "answer_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional classification or guidance for the expected answer.",
                        max_length=150,
                        null=True,
                        verbose_name="Answer Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essay Question (Manual/AI Graded)",
                "verbose_name_plural": "Essay Questions (Manual/AI Graded)",
            },
            bases=("content.question",),
        ),
        migrations.CreateModel(
            name="EssayPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="The question or prompt for the essay response.",
                        verbose_name="Prompt Text",
                    ),
                ),
                (
                    "rubric",
                    models.TextField(
                        blank=True,
                        help_text="Optional grading guidance for this specific prompt.",
                        null=True,
                        verbose_name="Rubric",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="content.essayquestion",
                        verbose_name="Related Essay Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essay Prompt",
                "verbose_name_plural": "Essay Prompts",
            },
        ),
        migrations.CreateModel(
            name="EssayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Question ID"
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        help_text="Student's essay response.",
                        verbose_name="Answer Text",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "sitting_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sitting ID"
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated feedback or scoring.",
                        null=True,
                        verbose_name="AI Feedback",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="content.essayprompt",
                        verbose_name="Prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essay Answer",
                "verbose_name_plural": "Essay Answers",
            },
        ),
    ]
