# Generated by Django 4.2.13 on 2025-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_essayquestion_essayprompt_essayanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayprompt",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
