# Generated by Django 4.2.13 on 2024-10-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_resources_file_type_alter_course_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="resources", name="file_type",),
    ]
