# Generated by Django 4.2.13 on 2024-10-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_remove_resources_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="file_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.category",
            ),
        ),
    ]
