# Generated by Django 4.2.13 on 2025-06-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_essayprompt_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="figure",),
        migrations.CreateModel(
            name="QuestionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="question_media/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("library", "Library"),
                            ("embed", "Embed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("embed_code", models.TextField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="content.question",
                    ),
                ),
            ],
        ),
    ]
