# Generated by Django 4.2.13 on 2025-06-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_remove_question_figure_questionmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmedia",
            name="file",
            field=models.FileField(default="null", upload_to="question_media/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionmedia",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="content.question",
            ),
        ),
    ]
