# Generated by Django 4.2.13 on 2024-10-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_resources_file_type_alter_course_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
