# Generated by Django 4.2.13 on 2025-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_questionmedia_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmedia",
            name="url_from_library",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
