# Generated by Django 4.2.13 on 2024-10-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.uploadedfile",
            ),
        ),
    ]
