# Generated by Django 4.2.13 on 2025-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_questionmedia_url_from_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmedia",
            name="type_from_library",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
