# Generated by Django 4.2.13 on 2024-10-04 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0016_lesson_uploaded_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="upload", name="file",),
        migrations.RemoveField(model_name="upload", name="student",),
        migrations.AddField(
            model_name="upload",
            name="approvers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="upload",
            name="title",
            field=models.CharField(default="title", max_length=255),
        ),
        migrations.AlterField(
            model_name="upload",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
