# Generated by Django 4.2.13 on 2024-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_remove_upload_file_remove_upload_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
