# Generated by Django 4.2.13 on 2025-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_questionmedia_type_from_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmedia",
            name="input_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
