# Generated by Django 4.2.13 on 2025-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_questionmedia_input_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="fail_text",
            field=models.TextField(
                blank=True,
                default="You didn’t pass this time. Review the material and try again.",
                help_text="Displayed if user fails.",
                verbose_name="Fail Text",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="success_text",
            field=models.TextField(
                blank=True,
                default="Congratulations! You've successfully passed the quiz.",
                help_text="Displayed if user passes.",
                verbose_name="Success Text",
            ),
        ),
    ]
