# Generated by Django 4.2.13 on 2024-10-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_alter_upload_approval_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(default="file", max_length=200),
        ),
    ]
