# Generated by Django 4.2.13 on 2024-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_lesson_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="source_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
