# Generated by Django 4.2.13 on 2025-06-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_alter_quiz_fail_text_alter_quiz_success_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="quiz", name="exam_material",),
        migrations.AddField(
            model_name="quiz",
            name="quiz_material",
            field=models.TextField(
                blank=True,
                help_text="Specify any external resources the test-taker is allowed to use during the quiz. Please separate each quiz material by a comma.",
                verbose_name="Quiz Materials",
            ),
        ),
    ]
