# Generated by Django 4.2.13 on 2025-06-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_remove_quiz_exam_material_quiz_quiz_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz_references/"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("upload", "Upload"), ("library", "Library")],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("url_from_library", models.URLField(blank=True, max_length=500)),
                ("type_from_library", models.CharField(blank=True, max_length=255)),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="content.quiz",
                    ),
                ),
            ],
        ),
    ]
