# Generated by Django 4.2.13 on 2024-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_credential_source_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="type",
            field=models.CharField(
                choices=[("thumbnail", "Thumbnail")], default="thumbnail", max_length=20
            ),
            preserve_default=False,
        ),
    ]
