# Generated by Django 4.2.13 on 2024-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="file_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
