# Generated by Django 4.2.13 on 2025-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_quizreference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz", old_name="allowRestart", new_name="allow_restart",
        ),
        migrations.RenameField(
            model_name="quiz", old_name="attemptsTaken", new_name="attempts_taken",
        ),
        migrations.RenameField(
            model_name="quiz", old_name="totalAttempts", new_name="total_attempts",
        ),
        migrations.RenameField(
            model_name="quiz", old_name="totalWarnings", new_name="total_warnings",
        ),
        migrations.RemoveField(model_name="quiz", name="singularExamRules",),
        migrations.AddField(
            model_name="quiz",
            name="singular_quiz_rules",
            field=models.TextField(
                blank=True,
                help_text="a set of rules for a specific quiz.",
                verbose_name="singular_quiz_rules",
            ),
        ),
    ]
