# Generated by Django 4.2.13 on 2024-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_resources_file_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="referencesEnabled",
            field=models.BooleanField(default=False),
        ),
    ]
