# Generated by Django 4.2.13 on 2024-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_course_referencesenabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
