# Generated by Django 4.2.13 on 2025-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_quiztemplate_templatecategoryselection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="create_quiz_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create_quiz_from1", "Quiz Template"),
                    ("create_quiz_from2", "Quiz"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quiz_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quiz_template_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="selected_quiz_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="selected_quiz_template_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
