# Generated by Django 4.2.13 on 2024-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_resources_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="uploadsEnabled",
            field=models.BooleanField(default=False),
        ),
    ]
