# Generated by Django 4.2.13 on 2025-06-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_lesson_create_quiz_from_lesson_quiz_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_type", models.CharField(blank=True, max_length=50, null=True)),
                ("passing_score", models.PositiveIntegerField(blank=True, null=True)),
                ("require_passing", models.BooleanField(default=False)),
                ("quiz_duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "quiz_attempts",
                    models.CharField(
                        blank=True, default="Unlimited", max_length=20, null=True
                    ),
                ),
                (
                    "maximum_warnings",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("randomize_order", models.BooleanField(default=False)),
                ("reveal_answers", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_config",
                        to="content.lesson",
                    ),
                ),
            ],
        ),
    ]
