# Generated by Django 5.0.1 on 2024-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_course_uploadsenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scorm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
