# Generated by Django 5.0.1 on 2024-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_course_scorm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='scorm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
