# Generated by Django 5.0.1 on 2024-10-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_lesson_scorm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='scorm_entry_point',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
