# Generated by Django 5.1.2 on 2025-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_uploadedfile_scorm_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
