version: 2
updates:
    # Adding new check for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    reviewers:
      - "openedx/arbi-bom"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/unit-tests/"
    schedule:
        interval: "weekly"
    reviewers:
      - "openedx/arbi-bom"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/verify-tests-count/"
    schedule:
        interval: "weekly"
    reviewers:
      - "openedx/arbi-bom"
